### ISSUE TITLE
Segfault after using workspace()

### ISSUE THREAD

**Issue by micahjsmith** [stevengj/Blosc.jl#19]
I get a segfault with the following commands in the REPL:
```
using Blosc
workspace()
using Blosc
exit()
```

The full error output can be seen here: https://gist.github.com/micahjsmith/60b4556d67c47665ba587b11afa1d6b7

See also:
```
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d* (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
Looking at [the Blosc source code](https://github.com/Blosc/c-blosc/blob/ddf31915925588ca073a92e6e21853e78cc162c7/blosc/blosc.c), it seems like it is not safe to call `blosc_init` twice, which is what will happen here (`__init__` is called twice).

One thing we could do instead is to call `blosc_set_nthreads(blosc_get_nthreads())`, which [from the source](https://github.com/Blosc/c-blosc/blob/ddf31915925588ca073a92e6e21853e78cc162c7/blosc/blosc.c) automatically calls `blosc_init` if it hasn't been initialized yet, and otherwise does nothing.

Another option might be to just not call `blosc_init` at all, since it looks from the source like `blosc_init()` is lazily called by any routine that needs it, but I'm wary of this because the Blosc documentation says you are supposed to call `blosc_init`.  Even the `set_nthreads` trick seems iffy according to Blosc/c-blosc#150, but since `g_initlib` is a `static` (unexported) variable I don't see much choice.

**Comment by FrancescAlted** [comment]
Perhaps https://github.com/Blosc/c-blosc/commit/5905212dcc2d11cb28694c4528ad677d35d360fb would help?

**Comment by stevengj** [comment]
@FrancescAlted, I think you also need a `if (!g_initlib) return;` check in `blosc_init` itself.

**Comment by FrancescAlted** [comment]
Good point.  Fixed in https://github.com/Blosc/c-blosc/commit/4b271d11e8832656c0956cdac2bfd6fff3b1cda8.

**Comment by stevengj** [comment]
Great, thanks!

**Comment by stevengj** [comment]
Should be fixed on the latest master by the bump to c-blosc 1.11.1
