### ISSUE TITLE
provide additional compressors besides blosclz

### ISSUE THREAD

**Issue by robertfeldt** [stevengj/Blosc.jl#3]
The default build of the Blosc package only came with the blosclz compressor. I checked the Blosc build instructions and followed the instructions to build libblosc with internal compressors. Updated build.jl file is in this gist:
https://gist.github.com/robertfeldt/a5433400bc0bdea3996c
(I did not have time to do a proper pull request, sorry). After installing with that build file I now have all 5 Blosc compressors:

```
julia> Blosc.compressors()
5-element Array{SubString{ASCIIString},1}:
  "blosclz"
  "lz4"
  "lz4hc"
  "snappy"
  "zlib"
```

and can use them all:

```
julia> using Base.Test
julia> for (comp, name, _) in Blosc.compressors_info()
       println("Compressor = $comp")
       Blosc.set_compressor(comp)
       for level=0:9
           for shuffle in (true, false)
               for i=1:2048
                   a = rand(Uint8, i)
                   ac = Blosc.compress(a, level=level, shuffle=shuffle)
                   info = Blosc.compressor_info(ac)
                   @test info.library == name
                   @test info.typesize == sizeof(Uint8)
                   @test info.shuffled == shuffle
                   @test Blosc.decompress(Uint8, ac) == a
               end
           end
       end
   end
Compressor = blosclz
Compressor = lz4
Compressor = lz4hc
Compressor = snappy
Compressor = zlib
```

**Comment by stevengj** [comment]
In practice, do many blosc users employ anything other than the default algorithm?   I get the impression that the cases where the other algorithms do significantly better are marginal enough that it is basically not worth worrying about (except for benchmarking).

**Comment by stevengj** [comment]
Also, this significantly complicates cross-platform portability, unless we build on all platforms with the same set of compression algorithms.

**Comment by robertfeldt** [comment]
Well, I use it but it's in my research so maybe I'm an outlier... :) But is there a downside to building the same set on all platforms? There is not a big difference in size of libs and it seems to cost very little; the blosc lib takes care of ensuring they all have the same interface etc. My 2 cents...

**Comment by jakebolewski** [comment]
I would be interested in ZLIB.

**Comment by stevengj** [comment]
The more components you want to build, the greater the complication of the build process (and the greater the probability of something going wrong, especially on Linux where we build from source).  

(@jakebolewski, why would you want to use deflate compression in a situation where you would apply Blosc?  Zlib seems badly suited to Blosc's main application of in-memory compression.  And deflate is already available in HDF5.jl, nor would you want to use it via the Blosc filter anyway since that would be incompatible with ordinary deflate-compression in HDF5.)

**Comment by FrancescAlted** [comment]
I think compiling Blosc with the complete set of its internal compressors is totally safe because the sources for them have been vendored and hence, their shipped versions are tested in most of the scenarios where Blosc is used.  In particular, my experience is that LZ4 is pretty good in a lot of scenarios.

Also, using zlib inside Blosc instead of deflate has the additional advantages that 1) it can use multiple threads right out of the box, 2) the shuffle filter is optimized for use SIMD on Intel platforms and 3) the shuffle filter can be applied in the blocks in which the chunks are split internally, so making the pipeline shuffle+compressor more cache friendly and hence faster.

**Comment by iamed2** [comment]
@stevengj Might you accept a PR to the build Makefile that would compile the bundled compressors? Looks like they describe how to do that with just Makefile options here: https://github.com/Blosc/c-blosc/blob/master/bench/Makefile

One reason I would like this is that Blosc actually provides a better interface to LZ4 than other LZ4 libraries, and this package is an excellent interface to Blosc.

**Comment by stevengj** [comment]
Is LZ4 significantly better than Blosc in common scenarios?

**Comment by iamed2** [comment]
On our data (lots of CSVs), yes. We're interested in only compressed size and decompression time, and in a Julia benchmark on our data found that Snappy is much better. 

```
Blosclz level 5
---
File size: 9066.94 KiB
Compression Factor: 30.92%
Decompression Time: 51513.79 μs
Compression Time: 31018.2 μs
```
```
Snappy
---
File size: 9066.94 KiB
Compression Factor: 21.96%
Decompression Time: 11851.14 μs
Compression Time: 37341.22 μs
```

And then in a benchmark with command line tools we found that LZ4 was better in both respects.

**Comment by stevengj** [comment]
Okay; a PR to add LZ4 seems acceptable.

**Comment by stevengj** [comment]
Closed by #26.

**Comment by jingpengw** [comment]
in case someone is still interested, I have a fork including all the compressors based on @robertfeldt 's build script. The fork only works in Linux though.
https://github.com/jingpengw/Blosc.jl

**Comment by robertfeldt** [comment]
Thanks, @stevengj , I tried to build from master now and it works great. Very nice and big thanks; much easier that there are now options in the "standard" Blosc julia package.
