### ISSUE TITLE
cc1: error: unrecognized command line option ‘-mavx2’

### ISSUE THREAD

**Issue by juliohm** [stevengj/Blosc.jl#30]
I tried to restart the build, but the error is persistent on Julia nightly and Linux: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/175836611#L240

**Comment by stevengj** [comment]
The `CHECK_AVX2 = $(shell if $(CC) $(CPPFLAGS) $(CFLAGS) -mavx2 -c -o shuffle-avx2.tmp shuffle-avx2.c; then echo 1; else echo 0; fi; rm -f shuffle-avx2.tmp)` runs `gcc -mavx2` to see if the flag is supported.  If it is not supported, it will print an error message, but the message is harmless.

Is the build actually failing or are you just worried because you are seeing the error message.

(We should probably have `> /dev/null 2>&1 ` to silence output from this test run of `gcc`.)

**Comment by juliohm** [comment]
@stevengj the build failed, but I think it was for a different reason, thank you for clarifying the error message, sorry for the noise. Closing the issue.
