### ISSUE TITLE
Sub-optimal binaries for Blosc library 

### ISSUE THREAD

**Issue by FrancescAlted** [stevengj/Blosc.jl#52]
In the attached benchmark ([sum-bench.jl.zip](https://github.com/stevengj/Blosc.jl/files/1983773/sum-bench.jl.zip)), a fresh install of the Blosc package on a Mac OSX box leaves to these timings:

```
$ julia sum-bench.jl 
  51.504 ms (0 allocations: 0 bytes)
  51.591 ms (3 allocations: 48 bytes)
  92.988 ms (754 allocations: 11.80 KiB)
  407.834 ms (754 allocations: 11.80 KiB)
  379.742 ms (750 allocations: 11.72 KiB)
  378.752 ms (0 allocations: 0 bytes)
```

When replaced the Blosc library by one that is compiled natively (via cmake) with:

```
$ cp ~/blosc/c-blosc/build/blosc/libblosc.1.14.3.dylib ~/.julia/v0.6/Blosc/deps/usr/lib/libblosc.1.14.3.dylib 
```

and re-running the benchmark, I get this:

```
$ julia sum-bench.jl 
  50.631 ms (0 allocations: 0 bytes)
  51.209 ms (3 allocations: 48 bytes)
  92.434 ms (754 allocations: 11.80 KiB)
  116.036 ms (754 allocations: 11.80 KiB)
  114.799 ms (750 allocations: 11.72 KiB)
  113.008 ms (0 allocations: 0 bytes)
```

The last three lines in the timings represent benchmarks using the Blosc libraries.  As can be seen, a native Blosc library performs around 3x faster than the binary that is being distributed.

**Comment by FrancescAlted** [comment]
Nothing obvious comes to my eyes.  Hmm, SSE2 is autodetected: how we can make sure that the builder has SSE2 available?  SSE2 is here since Pentium4, so this is probably the case.  Maybe the compiler version is very old?  I normally use clang that comes with Mac OSX with pretty optimal results.

**Comment by stevengj** [comment]
BloscBuilder uses cross-compilers to generate binaries for all platforms simultaneously, so maybe the SSE2 autodetection doesn't work when cross-compiling?  I don't really know much about cmake's cross-compilation support.

Ideally we should build binaries with support for both AVX2 and SSE2, and at runtime blosc would check whether the current CPU supports these and enable/disable those code paths accordingly.  My understanding is that c-blosc supports this (I see `cpuid` detection code in `shuffle.c`, for example), is that correct?

**Comment by stevengj** [comment]
@staticfloat, c-blosc's CMakeList uses [CMAKE_C_COMPILER_VERSION to detect whether AVX2 and SSE2 are supported](https://github.com/Blosc/c-blosc/blob/5d901610cd9224365ecba512a1319f53961e1dde/CMakeLists.txt#L203-L219).   It looks for gcc ≥ 4.7 or clang ≥ 3.2, apparently.  Shouldn't this work with the cross-compile environment?

I don't see CMAKE_C_COMPILER_VERSION defined in https://github.com/staticfloat/julia-docker/blob/master/crossbuild/cmake_toolchains/x86_64-apple-darwin14.toolchain … is this detected automatically by cmake, or is it something that should be set manually during cross-compilation?

**Comment by staticfloat** [comment]
Good questions.  First off, analyzing the `libblosc.dylib` file hosted from BloscBuilder, I see it already contains SSE2 (and SSSE3) instructions. but these likely aren't for the important routines and are just there because of compiler optimizations:

```
julia> BinaryBuilder.instruction_mnemonics("./libblosc.dylib")[2]
Dict{String,Int64} with 21 entries:
  "nop"      => 559
  "sse2"     => 401
  "call"     => 1707
  "sse4.2"   => 0
  "sse4.1"   => 0
  "aes"      => 0
  "pclmul"   => 0
  "586"      => 0
  "avx2"     => 0
  "3dnowext" => 0
  "mmx"      => 890
  "ssse3"    => 13
  "sse4a"    => 0
  "3dnow"    => 0
  "cpuid"    => 26
  "avx"      => 0
  "unknown"  => 139473
  "486"      => 4
  "686"      => 2065
  "sse3"     => 0
  "sse"      => 1014
```

But when I run the `cmake` command locally by using `BinaryBuilder.runshell(MacOS())`, (or look in the logs bundled with the `.tar.gz` file from BloscBuilder) it complains that it doesn't recognize the processor architecture:

```
CMake Warning at CMakeLists.txt:248 (message):
  Unrecognized system processor .  Cannot determine which hardware features
  (Clang 6.0.0) supports, so hardware-accelerated implementations will not be
  available.
```

This is because we hadn't defined `CMAKE_SYSTEM_PROCESSOR` inside of our toolchain files.  This [has been added](https://github.com/staticfloat/julia-docker/commit/4bb8f656c90c74c3f6f503bce9656c6278ba9b9a) and will pop up in the next release, but until then, I suggest you [add `-DCMAKE_SYSTEM_PROCESSOR=$(uname -p)` to your `build_tarballs.jl` bash script recipe](https://github.com/stevengj/BloscBuilder/pull/1).  This worked for me to silence the `cmake` warning above, and it generated a `libblosc.dylib` that has significantly more interesting instructions:
```
julia> BinaryBuilder.instruction_mnemonics("./libblosc.dylib")[2]
Info: Running privileged container via `sudo`, may ask for your password:
Dict{String,Int64} with 21 entries:
  "nop"      => 596
  "sse2"     => 1141
  "call"     => 1788
  "sse4.2"   => 0
  "sse4.1"   => 0
  "aes"      => 0
  "pclmul"   => 0
  "586"      => 0
  "avx2"     => 0
  "3dnowext" => 0
  "mmx"      => 1340
  "ssse3"    => 19
  "sse4a"    => 0
  "3dnow"    => 0
  "cpuid"    => 38
  "avx"      => 1137
  "unknown"  => 144087
  "486"      => 4
  "686"      => 2153
  "sse3"     => 0
  "sse"      => 1074
```

Critically, there are some `cpuid` instructions in there, which means that `libblosc` is hopefully smart enough to query the CPU at runtime and dispatch to the properly-optimized routine instead of just crashing on older (Core 2 is the floor of what we target) hardware.  That is what is meant by the new warnings I get during the audit phase, where it says:

```
Info: Analyzing minimum instruction set for lib/libblosc.1.14.3.dylib                                                             
Warning: libblosc.1.14.3.dylib contains a `cpuid` instruction; refusing to analyze for minimum instruction set, as it may dynamically select the proper instruction set internally.  Would have chosen sandybridge, instead choosing core2.   
```

**Comment by stevengj** [comment]
Thanks @staticfloat, I tagged a new BloscBuilder release to upload the new binaries, and will hopefully merge #53 soon to use them in Blosc.jl.

**Comment by stevengj** [comment]
@FrancescAlted, do a `Pkg.checkout("Blosc"); Pkg.build("Blosc")` to get the latest binaries; hopefully the performance should now match that of your manually built binaries.
